### ISSUE TITLE
Minecraft Version | Question

### ISSUE THREAD

**Issue by ItzRonaldMLG** [UltimateGamer200/UltraColor#3] opened 2021-05-24 11:02 UTC
Hello,

The plugin failed to create the database, do you know what happened? https://pastebin.com/cvuSfUk0

**Comment by UltimateGamer200** [comment] 2021-05-24 12:41
Really strange. Is there an error.log generated in the UltraColor plugin folder? If there is, could you send that, please? Thanks!

**Comment by ItzRonaldMLG** [comment] 2021-05-24 15:20
There is is no error.log

**Comment by UltimateGamer200** [comment] 2021-05-24 19:25
Hm, interesting. Well, I've just done some testing with v.1.2.4 on a 1.16.5 test network, with sub-servers connected to a database, and connections seem to be fine. You might want to check that **ALL** your database details are correct and then do a reboot. If that doesn't help, you might also want to check with the provider you're using to host your database and make sure it's not down and everything is fine there. I'm also planning to release v1.2.5 this week, so if neither of those works, you can try updating to that version when it comes out (I'll also add a "Debug" setting in the settings.yml file for that version, which you can use to debug mysql that can also help determine the issue). 

If that doesn't work, then I'll need some more information about what you're using database-wise (such as where your database being hosted (or the program if you're locally hosting it), type of database, and maybe protocol version) to farther determine the issue.

**Comment by UltimateGamer200** [comment] 2021-05-25 21:43
Good to know. I did release 1.2.5, so feel free to try it out when you get the chance!

**Comment by ItzRonaldMLG** [comment] 2021-05-26 15:51
This is the error: https://pastebin.com/equH3eJN

**Comment by UltimateGamer200** [comment] 2021-05-26 17:42
Hmm, I do notice that "ucolor_database" is unknown in the error you sent. Are you sure the database still exists? I also may need to reproduce this, so if you could give me the program you use to have your MySQL server on (and probably the version of the database as well), I might see if I could reproduce this error. If all else fails, I have a plugin mentor I can get in contact with to help determine what's causing the connection to your MySQL server to fail.

**Comment by ItzRonaldMLG** [comment] 2021-05-26 17:57
I did got some time and tried some things, i dont know exactly what caused it, but it works now. things like mysql server settings and just creating the database myself... I dont know how but something in the settings i changed worked.
Still, thanks for fast support :)

**Comment by UltimateGamer200** [comment] 2021-05-26 18:05
Yeah, sometimes even the random things we try to do end up being the solution. I figured it had to be something on your side considering things on my side and probably some others have theirs working as intended. Anyway, you're welcome! I'll go ahead and close this ticket now that this is solved. Hope you enjoy the new update!

**Closed by UltimateGamer200** 2021-05-26 18:05 UTC
Labels: Bug
